In [2]:
import numpy as np
import pandas as pd

SubFields = 2

NuPoints = 11
MuPoints = 11
AlphaPoints = 21

NuRange = [0.35, 0.45]
MuRange = [0.3, 0.7]
AlphaRange = [-60, -20]


print('Main field is cut into %.i subfields'%(SubFields**3))
Nus = np.linspace(NuRange[0],NuRange[1],SubFields+1)
Mus = np.linspace(MuRange[0],MuRange[1],SubFields+1)
Alphas = np.linspace(AlphaRange[0],AlphaRange[1],SubFields+1)

Nus = np.round(Nus,3)
Mus = np.round(Mus,3)
Alphas = np.round(Alphas,3)

print('Nu ranges:')
print(Nus)
print('%i Steps in each Nu range, example:'%(NuPoints))
print(np.linspace(Nus[0],Nus[1],NuPoints))
print('Mu ranges:')
print(Mus)
print('%i Steps in each Mu range, example:'%(MuPoints))
print(np.linspace(Mus[0],Mus[1],MuPoints))
print('Alpha ranges:')
print(Alphas)
print('%i Steps in each Alpha range, example:'%(AlphaPoints))
print(np.linspace(Alphas[0],Alphas[1],AlphaPoints))
print('Number of jobs by range: %i'%(NuPoints*MuPoints*AlphaPoints))
print('Max number of range to run: %.1f'%(10000/(NuPoints*MuPoints*AlphaPoints)))

Values = pd.DataFrame(dtype='float64')
for Nu in range(SubFields):
    for Mu in range(SubFields):
        for Alpha in range(SubFields):

            Range  = np.array([Nus[Nu], Mus[Mu], Alphas[Alpha],Nus[Nu+1], Mus[Mu+1], Alphas[Alpha+1]])
            Range  = np.reshape(Range,(2,3))
            Range1 = {'Nu':Range[0,0], 'Mu':Range[0,1], 'Alpha':Range[0,2]}
            Range2 = {'Nu':Range[1,0], 'Mu':Range[1,1], 'Alpha':Range[1,2]}

            Values = Values.append(Range1, ignore_index=True)
            Values = Values.append(Range2, ignore_index=True)

print(Values)
Values.to_csv('Ranges.txt', index=False)

Main field is cut into 8 subfields
Nu ranges:
[0.35 0.4  0.45]
11 Steps in each Nu range, example:
[0.35  0.355 0.36  0.365 0.37  0.375 0.38  0.385 0.39  0.395 0.4  ]
Mu ranges:
[0.3 0.5 0.7]
11 Steps in each Mu range, example:
[0.3  0.32 0.34 0.36 0.38 0.4  0.42 0.44 0.46 0.48 0.5 ]
Alpha ranges:
[-60. -40. -20.]
21 Steps in each Alpha range, example:
[-60. -59. -58. -57. -56. -55. -54. -53. -52. -51. -50. -49. -48. -47.
 -46. -45. -44. -43. -42. -41. -40.]
Number of jobs by range: 2541
Max number of range to run: 3.9
    Alpha   Mu    Nu
0   -60.0  0.3  0.35
1   -40.0  0.5  0.40
2   -40.0  0.3  0.35
3   -20.0  0.5  0.40
4   -60.0  0.5  0.35
5   -40.0  0.7  0.40
6   -40.0  0.5  0.35
7   -20.0  0.7  0.40
8   -60.0  0.3  0.40
9   -40.0  0.5  0.45
10  -40.0  0.3  0.40
11  -20.0  0.5  0.45
12  -60.0  0.5  0.40
13  -40.0  0.7  0.45
14  -40.0  0.5  0.40
15  -20.0  0.7  0.45
